[package]
name = "johalls-chess-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = { git = "https://github.com/INDA23PlusPlus/sieric-chess" }
rayon = "1.8.0"
